### ISSUE TITLE
Instructions on adding an external package not on hackage

### ISSUE THREAD

**Issue by codygman** [GuillaumeDesforges/haskell-nix-dev-template#6]
Not sure if this is in scope here or not. I'm having a hard time figuring it out from [the monorepo tutorial](https://github.com/fghibellini/nix-haskell-monorepo/tree/master/extra-deps) so perhaps a simplified way to do this in this template would be helpful to me and others.

**Comment by GuillaumeDesforges** [comment]
Will investigate, thanks.

EDIT:

In my opinion, this goes beyond the purpose of this repo.
What I wanted was a setup so that people would not need to write Nix expressions at first (only edit config file eventually).
This case enters the "you have to go further" realm.

I will add a link in the readme to the page you cited since the instructions seem clear to me there.

What I can do is setup an empty ./nix/extra-deps.nix and insert the lines required to override the Haskell packages from `pkgs`.

**Comment by GuillaumeDesforges** [comment]
Could you please see https://github.com/GuillaumeDesforges/haskell-nix-dev-template/pull/7 ?
